name = "echo-collector"
routes = [
  { pattern = "echo-collector.worker.hexly.ai", custom_domain = true }
]
workers_dev = false
preview_urls = false
main = "src/index.ts"
compatibility_date = "2025-05-01"

[[kv_namespaces]]
binding = "ECHO"
id = "c8b08f1809d2416db8f2c0270c0a04a9"

[vars]
ENVIRONMENT = "production"
